name: tlindell
favicon: null
layout_spectrum: 0.0467779440805316
typography_spectrum: 0.25577148236334324
title: Tyler Lindell
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6acbec'
    - '#171115'
    - '#ffffff'
    - '#2e5363'
    - '#bfbfbf'
  brandStrength: 0.9375
  lightness: 1
  saturation: 0.3125
  rhythmicContrast: 0.25
purpose: []
