name: tlindell
favicon: null
layout_spectrum: 0.0467779440805316
typography_spectrum: 0.25577148236334324
title: Tyler Lindell
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1e2832'
    - '#fefefe'
    - '#8a8a8a'
    - '#1e90fb'
    - '#d1504d'
  brandStrength: 1
  lightness: 0.75
  saturation: 0.5625
  rhythmicContrast: 0.25
purpose: []
