name: tlindell
favicon: null
layout_spectrum: 0.51162
typography_spectrum: 0.74405
title: Tyler Lindell
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6acbec'
    - '#171115'
    - '#ffffff'
    - '#2e5363'
    - '#bfbfbf'
  brandStrength: 0
  lightness: 0.875
  saturation: 0.1875
  rhythmicContrast: 0.5
purpose: []
